### PR TITLE
Update OpenSSL, fix depends, update default nodes

### PR DESCRIPTION
**Pull request by gradinkov**

### CODE REVIEW

**Comment by ajoslin** [comment]
Thanks!

Can you add the following nodes:

seed.pigeoncoin.cc:6969
seed2.pigeoncoin.cc:6969

**Comment by gradinkov** [comment]
Hello, first was already present, I added the second one.

**Comment by ajoslin** [comment]
Thanks. Will clone this and run it asap to make sure things are OK.

Busy today but might have a chance tonight.

**Comment by lukepighetti** [comment]
Implemented. Thank you.

**Pull request closed without merging**
